site_name: "tokenwiser"
extra_css: [style.css]
repo_url: https://github.com/koaning/tokenwiser
site_url: https://koaning.github.io/tokenwiser/
site_description: Bag of, not words, but tricks!
site_author: Vincent D. Warmerdam
use_directory_urls: false
nav:
  - Home: index.md
  - Scikit-Learn: guide/sklearn.md
  - spaCy: guide/spacy.md
  - API:
      - textprep: api/textprep.md
      - pipeline: api/pipeline.md
      - extension: api/extension.md
      - component: api/component.md
#      - model: api/model.md
  - FAQ: faq.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - from tokenwiser.textprep import *
            - from tokenwiser.pipeline import *
      watch:
        - tokenwiser
  - search
copyright: Copyright &copy; 2020 Maintained by <a href="https://twitter.com/fishnets88">Vincent</a>.
theme:
  name: material
  logo: token.png
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: white
    accent: teal
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      guess_lang: true
  - toc:
      permalink: true